name: koko_note
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  gsheets: ^0.5.0
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  http: ^1.1.0
  google_fonts: ^5.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  freezed: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
